name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make pkg
      run: make pkg
    - name: upload binary package
      uses: actions/upload-artifact@v4.3.3
      with:
        path: ./*.tar.gz
